import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Homepage from "./components/Homepage";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rezumers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Homepage />
      <Footer />
    </div>
  );
}
